### ISSUE TITLE
Compile java 8

### ISSUE THREAD

**Issue by MasterErik** [vsl1978/mybatis-generator-pluginsplus#1]
При компиляции под java 8 выдает кучу ошибок. Пробовал с вязаться с вами по Email. Нет ответа.

**Comment by vsl1978** [comment]
fixed in rev. 4ced81a0eec1424d5132cb346ae29493f6f96bda

**Comment by MasterErik** [comment]
Здравствуйте Владимир!

Есть еще проблемы при чистой установке.
mybatis-generaotr-plugunplus-test:test спотыкается на поиске ресурсов. Надо
перенести папку resources в src/main и поправить
<configurationFile>${basedir}/src/test/resources/db/generatorConfig.xml</configurationFile>
Так же не создается база данных. Можно
изменить connectionURL="jdbc:hsqldb:file:mybatis-generator-pluginsplus-tests/src/main/resources/db/testdb;ifexists=false;readonly=true"

Я хочу воспользоватся вашими плагинами, для подсчета количества записей при
удалении на MS SQL. Если метод delete что то возвращает, то надо добавить
sql после удаления
delete from CONTACT where ID = #{id};
select @@ROWCOUNT;

При пакетном выполнении запросов (<setting name="defaultExecutorType"
value="BATCH"/>) получаем число удалённых записей. Я хотел добавить такую
функциональность. Еще не полностью изучил ваши плагины. У вас есть такой
плагин?

2016-10-17 19:49 GMT+03:00 Vladimir Lokhov <notifications@github.com>:
